---
- name: install linux packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: 
    - ntp

- name: enable ntp
  sudo: yes
  service:
    name: ntp
    state: started


- name: Ensures .ssh dir exists
  file: path=/home/vagrant/.ssh state=directory

- name: Ensures /osd dir exists
  sudo: yes
  file:
    path: /osd
    state: directory
    mode: 0777
  
- name: copy ssh keys
  copy:
    src: "{{ item }}"
    dest: "/home/vagrant/.ssh/"
    owner: vagrant
    group: vagrant
    mode: 0600
  with_fileglob:
    - "{{ role_path }}/files/ssh/*"

# Example using key data from a local file on the management machine
- name: add authorized keys
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '{{ role_path }}/files/ssh/id_rsa.pub') }}"

- name: configure bash
  sudo: yes
  template:
    src: bashrc
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
